### ISSUE TITLE
What these numbers mean?

### ISSUE THREAD

**Issue by AdhamSalah5** [kariulele/PLOP-texture_segmentation#1]
plop(__, x, y)
what do x and y stand for and with changing what happens I'm asking if this code can segment different textures in an image or what?

**Comment by kariulele** [comment]
these numbers are respectively the number of points at the beginning of the segmentation and the distance limit between two points to merge them. you can play with them for your image to see which result you want. the less point you have the less bigpixel you'll have.

**Comment by AdhamSalah5** [comment]
mainly how the approach is implemented and how the texture is segmented?

**Comment by kariulele** [comment]
I honestly don't remember that much, it is a school project i did 3 years ago. I can go down in it again if you need. What do you want to use it for?

**Comment by AdhamSalah5** [comment]
I want to use this code to segment different textures in images as one of my bachelor project parts needs texture segmentation, can It do so? specifically for the furniture images, also what should the values I add for each photo, I tried to change many values as I can but always some bluelines are out of bounding.
